[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[lint]
# ... rest of lint config ...
exclude_lints = ["mixed-case-variable", "screaming-snake-case-immutable"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
